### PR TITLE
initial

### PR DESCRIPTION
**Pull request by fredericschmidt**
No changes... Apparently duplicate the files, I don't understand why...

### CODE REVIEW

**Comment by AStcherbinine** [comment]
Yeah that's because you added two repositories that are not supposed to be on the git (only generated locally when building the module): `omegapy.egg-info` and `build/lib/omegapy/`
image
image

You can remove them from your Git forked repo.

**Comment by fredericschmidt** [comment]
New try, with update of omega_data only ! For the moment read all the NAV the plane into the out_geom dict and only put phase in self

**Comment by AStcherbinine** [comment]
Looks much better, thanks! Indeed it's probably better to read all the NAV data.
Just a question about the L-geom: is there an actual difference with the C-geom? I know that the V channel is not co-aligned but I thought the C and L ones have the exact same fov?

**Comment by fredericschmidt** [comment]
Actually they are not perfectly co-aligned. At least the nav are not perfectly in the same geometry (in my test cube, the results is : 
0.3 degree = 15 km on Mars difference between V and C, 
0.1 degree = 5 km on Mars difference beetween C and L.
I would thus suggest to keep all planes !

I made an update for all data plane in NAV + V and L geom choice. Did you see it ?

**Comment by AStcherbinine** [comment]
Ok, thanks for the information!
Yes I can see your modifications, it looks good to me. I'm gonna merge them into the branch to make some tests, then include them into the main branch and upgrade the module to v3.2. ;)

**Pull request merged**
